website-ads: "https://gachcloud.net/minomc"
server-ip: "Ê™á´‡á´›á´€.á´á´„á´›á´œÊ€á´›ÊŸá´‡.Ñ…Êá´¢"

# Báº¡n cÃ³ thá»ƒ thÃªm nhiá»u dÃ²ng vÃ o Ä‘Ã¢y náº¿u thÃ­ch
death-messages:
  - "Â§c%victim% Â§fÄ‘Ã£ bá»‹ giáº¿t bá»Ÿi Â§b%killer% Â§f(Â§cğŸ¤ %health%Â§f)"
  - "Â§c%victim% Â§fÄ‘Ã£ bá»‹ mukbang bá»Ÿi Â§b%killer% Â§f(Â§cğŸ¤ %health%Â§f)"
  - "Â§c%victim% Â§fÄ‘Ã£ bá»‹ biáº¿n thÃ nh tÃºi chanel chÃ­nh hÃ£ng khi Ä‘áº¥u tay Ä‘Ã´i vá»›i Â§b%killer% Â§f(Â§cğŸ¤ %health%Â§f)"
  - "Â§c%victim% Â§fÄ‘Ã£ bá»‹ Ä‘Æ°a vÃ o há»‘ Ä‘en vÅ© trá»¥ khi chiáº¿n Ä‘áº¥u vá»›i Â§b%killer% Â§f(Â§cğŸ¤ %health%Â§f)"
  - "Â§c%victim% Â§fbá»‹ nÆ°á»›ng chÃ­n 7 pháº§n bá»Ÿi Ä‘áº§u báº¿p Â§b%killer% Â§f(Â§cğŸ¤ %health%Â§f)"
  - "Â§c%victim% Â§fbá»‹ Â§b%killer% Â§fÄ‘Ã¡nh vÄƒng vá» tuá»•i thÆ¡ Â§f(Â§cğŸ¤ %health%Â§f)"
  - "Â§c%victim% Â§fbá»‹ xá»­ lÃ½ gá»n láº¹ bá»Ÿi Â§b%killer% Â§fnhÆ° bÃ¡t mÃ¬ tÃ´m Ä‘Ãªm muá»™n Â§f(Â§cğŸ¤ %health%Â§f)"
  - "Â§c%victim% Â§fÄ‘Ã£ thÃ nh mÃ³n snack cho Â§b%killer% Â§fnhÃ¢m nhi Â§f(Â§cğŸ¤ %health%Â§f)"
  - "Â§c%victim% Â§fÄ‘Ã£ bá»‹ Â§b%killer% Â§fÄ‘Æ°a Ä‘i nghá»‰ mÃ¡t vÄ©nh viá»…n Â§f(Â§cğŸ¤ %health%Â§f)"
  - "Â§c%victim% Â§fÄ‘Ã£ bá»‹ Ä‘Ã¡ khá»i hÃ nh tinh bá»Ÿi Â§b%killer% Â§f(Â§cğŸ¤ %health%Â§f)"
  - "Â§c%victim% Â§fkhÃ´ng chá»‘ng ná»•i Ã¡p lá»±c tá»« Â§b%killer% Â§f(Â§cğŸ¤ %health%Â§f)"
  - "Â§c%victim% Â§fÄ‘Ã£ tan biáº¿n nhÆ° lá»i há»©a cá»§a ngÆ°á»i yÃªu cÅ© khi gáº·p Â§b%killer% Â§f(Â§cğŸ¤ %health%Â§f)"
  - "Â§c%victim% Â§fÄ‘Ã£ bá»‹ gÃµ Ä‘áº§u vÃ´ cá»±c bá»Ÿi Â§b%killer% Â§f(Â§cğŸ¤ %health%Â§f)"
  - "Â§c%victim% Â§fÄ‘Ã£ bá»‹ hoÃ¡ Ä‘Ã¡ bá»Ÿi Ã¡nh nhÃ¬n chÃ­ máº¡ng cá»§a Â§b%killer% Â§f(Â§cğŸ¤ %health%Â§f)"
  - "Â§c%victim% Â§fbá»‹ tiá»…n Ä‘i bá»Ÿi Â§b%killer% Â§ftheo phong cÃ¡ch 'bÃ¡n hÃ nh táº­n cá»­a' Â§f(Â§cğŸ¤ %health%Â§f)"
  - "Â§c%victim% Â§fÄ‘Ã£ bá»‹ bÃ³n hÃ nh táº­p thá»ƒ bá»Ÿi Â§b%killer% Â§f(Â§cğŸ¤ %health%Â§f)"

unknown-death-messages:
  - "Â§c%victim% Â§fÄ‘Ã£ cháº¿t khÃ´ng rÃµ nguyÃªn nhÃ¢n."
  - "Â§c%victim% Â§ftá»± nhiÃªn lÄƒn Ä‘Ã¹ng ra cháº¿t nhÆ° má»™t cÃº lag."
  - "Â§c%victim% Â§fbiáº¿n máº¥t nhÆ° cÃº phÃ¡p tin nháº¯n lá»—i."
  - "Â§c%victim% Â§fÄ‘Ã£ rá»i khá»i tháº¿ giá»›i nÃ y má»™t cÃ¡ch tháº§n bÃ­."
  - "Â§c%victim% Â§fbá»‘c hÆ¡i nhÆ° giÃ³ mÃ¹a khÃ´ng bÃ¡o trÆ°á»›c."

discord-link: "https://discord.gg/UargGfvtTy"

chat-format: "{prefix}{name}&r: {message}"
killstreak:
  enable: true
  prefix: "&c&l[Kill Streak] "
  every_n_kills: 5 # Announce every 5 kills (5, 10, 15, etc.)
  message: "{prefix} &e%player% Ä‘ang lÃ  káº» há»§y diá»‡t! Háº¯n Ä‘ang á»Ÿ chuá»—i kill %streak%!"
  shutdown:
    enable: true
    message: "{prefix} &e%player% Ä‘Ã£ bá»‹ cháº¥m dá»©t sau chuá»—i kill %streak%!"